### ISSUE TITLE
Do you have plans to update pypi.org with the latest version?

### ISSUE THREAD

**Issue by oPromessa** [TomMeHo/vsMetaFileEncoder#5]
Great tool and great job @TomMeHo !!!

I'm successfully using it to get Movies metadata from IMDB into my Synology Video Station Library.

Quick question, on pypi.org this version is not yet available. There is a similar one but with another name VsMetaFileEncoder whereas here the module to import is called vsmetaCodec.

Do you have plans to update it in pypi.org to facilitate importing into my project?

I think it would also be useful to have a full working example which I can add here if you'd like.

Thanks!

**Comment by TomMeHo** [comment]
Yes, I have. I'll provide another release on Pypi (never did on pipit.org - or they mirroring Pypi?).
Pleae give me a few days to find time for it.
Btw: you're welcome to contribute an example, if you want.

**Comment by oPromessa** [comment]
Sorry. Was a typo ;). It's pypi.org !!!

**Comment by TomMeHo** [comment]
Hi,
I've just published [version 1.1.1 on pypi.org](https://pypi.org/project/vsmetaEncoder/). 
Thank you for contributing,
Thomas

**Comment by TomMeHo** [comment]
.
